// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACqT54Gs7kFLR9L0mxBywlGn3tlb2Nko0',
    appId: '1:874430072046:web:9f7e282ff5b05895eb1fff',
    messagingSenderId: '874430072046',
    projectId: 'drug-traceability-system-d89c1',
    authDomain: 'drug-traceability-system-d89c1.firebaseapp.com',
    storageBucket: 'drug-traceability-system-d89c1.firebasestorage.app',
    measurementId: 'G-4BLHL8MN0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZARaSSKIpJgw2Av-i-oRR5951hixPpps',
    appId: '1:874430072046:android:e8d27eb2f331d147eb1fff',
    messagingSenderId: '874430072046',
    projectId: 'drug-traceability-system-d89c1',
    storageBucket: 'drug-traceability-system-d89c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOu9MFxRz5cWHphdBbEGc5GaB2j9-D0w',
    appId: '1:874430072046:ios:0e6b22157ec5f7b6eb1fff',
    messagingSenderId: '874430072046',
    projectId: 'drug-traceability-system-d89c1',
    storageBucket: 'drug-traceability-system-d89c1.firebasestorage.app',
    iosBundleId: 'com.example.drugTraceabilityMobile',
  );
}
